### ISSUE TITLE
Define how we extend ICA vocabs and schemas to support country, region and super-region concepts.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/ica-project#10]
We decided to keep the country, region and super-region extensions as simple as possible by creating 3 new vocabularies, namely country-ICA, region and super-region. region will be distinct from the vcard:region used in Co-ops UK data.

So the ICA csv schema will need to be updated to map to the new rdf terms. We won't make use of implicit relationships between country- region and super-region at this stage.

We want to do this in a way that doesn't reguire changes to other project's loaders.

**Comment by wu-lee** [comment]
Country lists here: https://github.com/SolidarityEconomyAssociation/sea-map/issues/104

**Comment by wu-lee** [comment]
I'm drafting a new SKOS file for countries (and later, region, superregion). I plan to write it in .ttl, since that seems far more concise and readable than RDF, then convert that to RDF. I'm using the `activities.skos` file converted to .ttl as a starting point.

Anyway, one of the first declarations defines authors and contributors to the definition, with email addresses. I am not sure what to put here, presumably the two of us, but the main thing I hesitate at is adding an email address. @ColmMassey, Do you want your usual email embedded in a file which is likely to be published on the internet for general addition to spammer databases? (I still get spam aimed at estate agents from once publishing my email address in code on a solicitor's website, likewise to the one I used on CPAN, so I probably want to use something other than my main address.) Or is there another email address we could use for you?

**Comment by ColmMassey** [comment]
> I plan to write it in .ttl, since that seems far more concise and readable than RDF, then convert that to RDF.

Are they not all rdf. What you refer to as RDF is XML-RDF 

But I agree Turtle is much more readable.

**Comment by ColmMassey** [comment]
> Or is there another email address we could use for you?

How about creating a dedicated one, like ess@lod.coop?

**Comment by wu-lee** [comment]
I think you're correct, it's all RDF, I was just thinking in terms of the file extension. Searching for the canonical name it seems to be [RDF/XML][1].

We could create a dedicated one, yes - is there is a simple way to do this currently with the lod.coop domain?  Presumably the DotCoop domain panel might have some facility for setting up forwarding aliases as least.

I suspect we'll need a lot of tweaks to get this right, so I'll make a draft and publish it on a branch on the map-sse project. Initial stab here, with just one term:

https://github.com/SolidarityEconomyAssociation/map-sse/blob/ica10-draft-locality-vocabs/vocabs/standard/countries.ttl

There are more things, such as the publisher. In fact, this seems inaccurate on all the vocab now, the publisher is presumably goed ol' SEA, and not RIPESS?


[1]: https://en.wikipedia.org/wiki/RDF/XML

**Comment by ColmMassey** [comment]
> is there is a simple way to do this currently with the lod.coop domain?

is that a question for WebArchitects or Dotcoop?

**Comment by ColmMassey** [comment]
> Presumably the DotCoop domain panel might have some facility for setting up forwarding aliases as least.

They no longer provide any hosting services. Panel seems pretty sparse of functionality. Where are the redirections from lod.coop to prod.solidarityeconomy hosted?

**Comment by wu-lee** [comment]
```
nick@mie-goreng:~$ host -t mx lod.coop
lod.coop has no MX record
```

So it looks like lod.coop doesn't get mail, period.  However, I expect it could be configured to have an MX record via the DotCoop registry account, and that this could then be set to point to WebArchitects (or wherever). Then things would (I think) work however it works for solidarityeconomy.coop, which also uses WA for its mail transfer.

**Comment by ColmMassey** [comment]
We should create a ticket to address this issue later.

**Comment by wu-lee** [comment]
Checking the Dublin Core specs, I don't actually think we need to put emails on the contributors/authors lists, or even the names of people...  

These specs seem big on intimidating formality and small on guidance or examples. And despite the formality it does seem hard to pin down what is and what isn't allowed, which in turn seems to make it hard to interpret these properties algorithmically. Things like the [`language` term][1] in the `elements/1.1` namespace are only *advised* to be BCP-47 (which is itself complex); not only that there seem be be duplicate-named terms in the `terms` and `elements/1.1` namespaces, without a clear guidance on which to use.  So it seems you can stick pretty much anything in, perhaps even invent yet another standard; therefore caveat emptor.

I'd like to say that we should keep it simple, but this is hard live up to because there's too many ways to do it.

Anyway: I've made a few tweaks to the bare-bones countries.ttl file, with one each of a vocabulary and a term definition.  What I'd like to do is use this as a template for all the other new vocabs, defining things only in English at first. @ColmMassey, can you take a look at the properties I've defined and let me know if they seem appropriate?

I am writing something to expand the countries data I have into a set of vocabs and a definition of what contains what. I presume I should use the [osspatialrelations:within][2] property for the latter?

- https://en.wikipedia.org/wiki/Dublin_Core
- Guides to using Dublic Core
  - https://omeka.org/classic/docs/Content/Working_with_Dublin_Core/
- Specs:
  - https://www.dublincore.org/specifications/dublin-core/dcmi-terms/
    - Terms namespace: http://purl.org/dc/terms/
      - https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#section-2
    - Elements 1.1 namespace: http://purl.org/dc/elements/1.1/
      - https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#section-3
  - https://www.dublincore.org/specifications/dublin-core/dcmes-qualifiers/

[1]: https://www.dublincore.org/specifications/dublin-core/dcmi-terms/elements11/language/
[2]: https://data.ordnancesurvey.co.uk/ontology/spatialrelations/within

**Comment by wu-lee** [comment]
A few more questions @ColmMassey :
- Is there a definitive source for the ICA locality data, preferably online? (So I can hook up any conversion directly to this, and avoid or minimise future manual updates.)
- Do they have any identifiers for country/region/super-region we should incorporate? (Even if these are names, I'm looking for whatever it is they use as unique identifiers for these things.)
- Where they differ from the "official" names (in whatever sense), do the ICA want us to preserve the country names I see in https://github.com/SolidarityEconomyAssociation/open-data/issues/67#issue-797092541 in labels, or are these simply for guidance? (Or internal unique identifiers, see last question. If they do want these shown in user interfaces, this will make the job of internationalisation of labels harder, since it means we can't simply use the ready-made names from other sources.)
- I presume we should expand the ICA list to include definitions for the whole set of ISO-3166-1 countries? (From the table you posted, it's missing a significant number.)
- Should we actually include the term "International" here? It doesn't really fit into the category of "country". It seems more like another category, perhaps a single-term category one level up from "super-region"
- Perhaps this issue should be moved to the `map-sse` project?

**Comment by wu-lee** [comment]
Useful resource here, Debian's collection of internationalisation data: 

https://salsa.debian.org/iso-codes-team/iso-codes

Similarly useful, the Ruby module [Carmen][1] derives its data from this. Another useful Ruby module is [NormalizeCountry][2], which references similar projects like `Carmen` in its documentation.It's not clear to me where `NormalizeCountry` gets its data from, however.

[1]: https://github.com/carmen-ruby/carmen
[2]: https://github.com/sshaw/normalize_country

**Comment by wu-lee** [comment]
Ah, I also see a more comprehensive list of ICA regions/countries in a file `ICA/country regions.xlsx` on the SEA Nextcloud share. Presume I should use this to address point 4 above.

**Comment by wu-lee** [comment]
I've matched up the ICO data I have with the ICA data from that spreadsheet on the ICO country code, and found cases which don't match (one from ICA missing from ICO, and several vice versa, but not as many as before).

I've imported the matches into a new tab on it called "ICO-ICA reconciliation". Possibly the ICA need to update their database if it doesn't match the ICO country list? (Or have updated? This file's timestamp was a year or so old.)

I think I need this list fully reconciled and signed off with you and the ICA, @ColmMassey, before I can then generate the vocabs and a `within` mapping which has any authority. Specifically, look at the fields where there is a FALSE value in the `ICO-Name-Match?` or `ICO-Code-Match?` columns. These are where the country names and/or codes differ.  Then we need regions and super-regions defined for all countries.

**Comment by wu-lee** [comment]
Best effort country vocabs now present on the `ica10-draft-locality-vocabs` branch, pending answers to questions above.

- https://github.com/SolidarityEconomyAssociation/map-sse/blob/ica10-draft-locality-vocabs/vocabs/standard/countries.ttl
- https://github.com/SolidarityEconomyAssociation/map-sse/blob/ica10-draft-locality-vocabs/vocabs/standard/regions.ttl
- https://github.com/SolidarityEconomyAssociation/map-sse/blob/ica10-draft-locality-vocabs/vocabs/standard/super-regions.ttl

Notes:
- No 'international` term. Need to decide whether to include that.
- Needs translations for regions and super-regions. EN, FR, ES, DE and ZH translations for countries included, because I can.

**Comment by wu-lee** [comment]
Queries nominally work on current dev server endpoint when new .skos files imported too, although names need to be tweaked for this test query (because purl.org is used in the original .skos)

Example query:
```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?scheme ?term ?label
WHERE {
  { # vocabulary info
    ?scheme a skos:ConceptScheme; dc:title ?label.
    FILTER(?scheme IN (
    <https://w3id.solidarityeconomy.coop/essglobal/V2a/standard/activities-ica/>,
    <http://purl.org/essglobal/standard/countries/>,
    <http://purl.org/essglobal/standard/regions/>,
    <http://purl.org/essglobal/standard/super-regions/>,
    <https://w3id.solidarityeconomy.coop/essglobal/V2a/standard/organisational-structure/>
    ))
  }
  UNION
  { # term info
    ?term
       a skos:Concept;
       skos:inScheme ?scheme.
    OPTIONAL { ?term skos:prefLabel ?label. }
    { ?term skos:inScheme <https://w3id.solidarityeconomy.coop/essglobal/V2a/standard/activities-ica/> }
    UNION
    { ?term skos:inScheme <http://purl.org/essglobal/standard/countries/> }
    UNION
    { ?term skos:inScheme <http://purl.org/essglobal/standard/regions/> }
    UNION
    { ?term skos:inScheme <http://purl.org/essglobal/standard/super-regions/> }
    UNION
    { ?term skos:inScheme <https://w3id.solidarityeconomy.coop/essglobal/V2a/standard/organisational-structure/> }
    FILTER (langMatches(lang(?label), "en") || langMatches(lang(?label), "fr") || langMatches(lang(?label), "pt") || langMatches(lang(?label), "es") || langMatches(lang(?label), "de"))
  }
}```

**Comment by wu-lee** [comment]
@ColmMassey 
Having extracted a list of countries from the raw ICA initiative CSV from Nextcloud, and matched them to names in the `ICA/country regions.xlsx` spreadsheet (which is my main index linking alpha-2 codes to ICA country names, but a bit old), here are the discrepancies.

- These names are present in ICA data, but aren't linked to an ISO country name in the spreadsheet table, because
  - the ICA name in the spreadsheet differs from any used in the data now, but this is OK because they can be manually matched - **no action required**:
    - *Palestine* (`PS`)
    - *Tanzania* (`TZ`)
    - *Côte d’Ivoire* (`CI`)
    - *Eswatini* AKA Swaziland (`SZ`)
    - *Iran* (`IR`)
    - *Korea*: This could be the Republic of Korea (`KR`) or the Democratic People's Republic of Korea (`KP`) but from the map, these are in `KR`
    - *Congo*: This could be the Republic of Congo (`CG`), or the Democratic Republic of Congo (`CD`), but from the map, this is in `CD`
  - the ICA name *in the spreadsheet table* (not the initiatives CSV) does not match any ISO country - **no action required, possibly a mistake or name change**:
    - *Serbia and Montenegro* 
  - the name in the ICA data is *International* - **we need to decide how to represent this in linked-data** (there are five cases in current ICA data, they all have *International* for country, region and super-region).
- These names are in the ISO countries list but not present in the ICA spreadsheet table or data. **We should add these with a region/super-region, proposal included**:
  - *Saint Barthélemy* (`BL`). I think this is in the region *Caribbean Countries*, which is in the super-region *Americas*
  - *Saint Martin (French part)* (`MF`). I think this is in the region *Caribbean Countries*, which is in the super-region *Americas*

**In order to avoid doing this checking and matching over and over, we need the ICA to start using ISO country codes rather than country names and include them in the data exports (names can vary arbitrarily or be ambiguous).**

**We also need the ICA to include their region and super-region definitions, with whatever unique identifiers they use as well as names (ditto)**

I will add the [ISO-3166-1 *official country names*][1] (not the *names*, which are typically shorter) as `prefLabel`s in the vocabulary.  I will add the *names* as `altLabel`s. The labels in the drop-downs will therefore be the official names. (I'd like them to be short, but it seems wrong to add the official name as the `altLabel`, and unfortunately there are permitted to be multiple or zero `altLabels`, and there is no way to [annotate the labels][2] I know of.)

For now I've invented some identifiers to use in the vocabularies, **we can propose these if the ICA don't have their own**:

```
RID	Region	SRID	Super-region
AF-CE	Central Africa	AF	Africa
AF-EA	East Africa	AF	Africa
AF-NO	North Africa	AF	Africa
AF-SO	Southern Africa	AF	Africa
AF-WE	West Africa	AF	Africa
AM-CB	Caribbean countries	AM	Americas
AM-CE	Central America	AM	Americas
AM-NO	North America	AM	Americas
AM-SO	South America	AM	Americas
AP-CE	Central Asia	AP	Asia+Pacific
AP-EA	East Asia	AP	Asia+Pacific
AP-ME	Middle East	AP	Asia+Pacific
AP-OC	Oceania	AP	Asia+Pacific
AP-SO	South Asia	AP	Asia+Pacific
AP-SE	South East Asia	AP	Asia+Pacific
EU-EA	Europe (Eastern)	EU	Europe
EU-WE	Europe (Western)	EU	Europe
```

[1]: https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/data/iso_3166-1.json
[2]: https://www.w3.org/2006/07/SWD/wiki/SkosDesign/AnnotationOnLabel.html

**Comment by ColmMassey** [comment]
>     * _in the spreadsheet table_

Can you clarify what is meant here by _spreadsheet table_ ?

**Comment by ColmMassey** [comment]
> the ICA name in the spreadsheet differs from any used in the data now, but this is OK because they can be manually matched - **no action required**:
> 
>     * _Palestine_ (`PS`)

I think your script for generating this list of mismatches may be having an issue with the commas used in some titles, because in the ICA data Palestine is listed as _Palestine, State of_  which seems identical to the ISO name?

**Comment by wu-lee** [comment]
> Can you clarify what is meant here by _spreadsheet table_ ?

I'd link to it but I have access via a shared Nextcloud link which won't be the same as the one you'd be seeing. But I mean the table on the "ISO/ICA reconciliation" tab of the spreadsheet `country regions.xlsx` in the ICA directory.

**Comment by wu-lee** [comment]
> > the ICA name in the spreadsheet differs from any used in the data now, but this is OK because they can be manually matched - **no action required**:
> > ```
> > * _Palestine_ (`PS`)
> > ```
> 
> I think your script for generating this list of mismatches may be having an issue with the commas used in some titles, because in the ICA data Palestine is listed as _Palestine, State of_ which seems identical to the ISO name?

The script does a simple string equality, nothing fancy.

I think the problem is that the table (mentioned in the last comment) has the ISO name *Palestine, State of*, but the ICA name *Palestinian Territory, Occupied*. I expect that this table used ICA names current at the time it was created, but that ICA have updated the name in their data to match the now current ISO country name(s). In other words, the table is a bit out of date.

**Comment by ColmMassey** [comment]
Questions/Requests for ICA
- Ask if they use country identifiers in their database, 
- Ask to migrate to use 2 letter ISO code for country,
- Ask to migrate to use identifiers for Region/Super region,
- Ask to distinguish between Country as part of address of members' headquaters from its Juristiction/Territory/Area of activity,
 - Stop using the term International, but use Region/Super region identifyier in the new Juristiction column rather than a country.
