### ISSUE TITLE
Add ICA logo

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/ica-project#5]
Can we add this logo to bothdev and prod ICA maps?

![Alliance_multilingual](https://user-images.githubusercontent.com/1162642/99152285-cd871a80-2698-11eb-909c-adcc76266950.png)

**Comment by wu-lee** [comment]
I  find that although an option to include a logo is implemented, originally for the DotCoop map, the logo size is kinda hardwired to 100x200px.  As such. this logo gets warped into that aspect box, and looks squished up.

I can readjust this so that (say) the height is fixed and the logo itself determines the aspect.

However, the logo is on the lower right, and as such needs to avoiding the zoom control.  It would probably be more aesthetic, and certainly easier, to put it lower left. Which would then also apply to DotCoop, when it gets a sea-map upgrade - because I'm not proposing adding any configurable position, just to try and accomodate a range of logo aspect-ratios.

Is that ok @ColmMassey , or do you think someone would care that the sea-map logo position is moved to the lower left?

**Comment by ColmMassey** [comment]
> I can readjust this so that (say) the height is fixed and the logo itself determines the aspect.

Sounds sensible.

**Comment by ColmMassey** [comment]
> Do you think someone would care that the sea-map logo position is moved to the lower left? 

They might, but probably not very loudly. We can deal with if they do. Go fo rmoving it to the left.

**Comment by wu-lee** [comment]
Hm, actually, the logo then gets overlaid by the pop-out sidebar.  I anticipate this might make complaints louder. Perhaps top right?

I also see that the logo is wide enough that it won't fit onto a phone display. I will need to add some device-responsive special cases to shrink it down for that case. 

So I've added these, and deployed to dev. You might want to check this visually yourself.

**Comment by ColmMassey** [comment]
Looks good to me om a few devices.
